GET https://mkvdrama.net/781538-perfect-crown
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Accept: aplication/html,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
# Accept-Language: en-US,en;q=0.5
# Accept-Encoding: gzip, deflate
Connection: keep-alive
# Upgrade-Insecure-Requests: 1
