events {}
http {
    upstream flaresolverr_backend {
        # Docker embedded DNS resolves service name to all replicas automatically
        server flaresolverr:8191; 
    }

    server {
        listen 8191;
        location / {
            proxy_pass http://flaresolverr_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
